# Generated by Django 5.1 on 2025-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('issue_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('issue_key', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('assignee', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('issuetype', models.CharField(max_length=100)),
                ('issuetype_description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('all_fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('issue_id', 'project'), name='unique_issue')],
                'unique_together': {('issue_id', 'project')},
            },
        ),
    ]
