# Generated by Django 5.1 on 2024-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('issuetype', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('assignee', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter', models.CharField(blank=True, max_length=100, null=True)),
                ('all_fields', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssueType',
            fields=[
                ('issuetype_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('issuetype_id', 'name', 'domain')},
            },
        ),
    ]
