# Generated by Django 5.1.8 on 2025-06-23 12:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('simplified', models.BooleanField()),
                ('projectTypeKey', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('accountId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=255)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('timeZone', models.CharField(max_length=100)),
                ('accountType', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('fieldtype', models.CharField(max_length=50)),
                ('from_value', models.CharField(blank=True, max_length=255, null=True)),
                ('to_value', models.CharField(blank=True, max_length=255, null=True)),
                ('fromString', models.TextField(blank=True, null=True)),
                ('toString', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jirahistory')),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('issue_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('issue_key', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('time_mined', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duedate', models.DateTimeField(blank=True, null=True)),
                ('timeoriginalestimate', models.IntegerField(blank=True, null=True)),
                ('timeestimate', models.IntegerField(blank=True, null=True)),
                ('timespent', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jira.jiraissue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraproject')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='jira.jirauser')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='jira.jirauser')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to='jira.jirauser')),
            ],
        ),
        migrations.AddField(
            model_name='jirahistory',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.CreateModel(
            name='JiraCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('repository_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue')),
            ],
        ),
        migrations.CreateModel(
            name='JiraComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue')),
            ],
        ),
        migrations.CreateModel(
            name='JiraChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField()),
                ('progress', models.CharField(max_length=50)),
                ('completed', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue')),
            ],
        ),
        migrations.CreateModel(
            name='JiraActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_value', models.CharField(blank=True, max_length=100, null=True)),
                ('from_value', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue')),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=50)),
                ('link_direction', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='jira.jiraissue')),
                ('linked_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to='jira.jiraissue')),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuetype', models.CharField(max_length=100)),
                ('issuetype_description', models.TextField(blank=True, null=True)),
                ('hierarchyLevel', models.IntegerField(default=0)),
                ('subtask', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue')),
            ],
        ),
        migrations.CreateModel(
            name='JiraSprint',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
                ('boardId', models.BigIntegerField()),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('completeDate', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issues', models.ManyToManyField(related_name='sprints', to='jira.jiraissue')),
            ],
        ),
    ]
