# Generated by Django 5.1.8 on 2025-08-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiracommit',
            name='repository_id',
        ),
        migrations.AddField(
            model_name='jiracommit',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jira_commits', to='utils.repository'),
        ),
        migrations.AlterField(
            model_name='jiraactivitylog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='jira.jirauser'),
        ),
        migrations.AlterField(
            model_name='jiracomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='jira.jirauser'),
        ),
        migrations.AlterField(
            model_name='jirahistory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='jira.jirauser'),
        ),
    ]
