# Generated by Django 5.1 on 2025-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='time_mined',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
