# Generated by Django 5.1 on 2025-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JiraIssueType',
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='issuetype_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
