# Generated by Django 5.1 on 2025-03-20 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_jiraissue_commits_jiraissue_time_mined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='time_mined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
