# Generated by Django 5.1.8 on 2025-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_remove_jiracommit_repository_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiracommit',
            name='repository_name',
            field=models.CharField(blank=True, help_text='Nome do repositório para consultas rápidas', max_length=255, null=True),
        ),
    ]
