# Generated by Django 5.1 on 2025-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_jiraissue_time_mined'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='commits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='time_mined',
            field=models.FloatField(blank=True, help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
    ]
