# Generated by Django 5.1.8 on 2025-11-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_jiracommit_repository_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
