# Generated by Django 5.1 on 2025-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_alter_jiraissue_time_mined'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('issues', models.ManyToManyField(related_name='sprints', to='jira.jiraissue')),
            ],
        ),
    ]
