# Generated by Django 5.1 on 2025-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_jiraissue_commits_alter_jiraissue_time_mined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='commits',
            field=models.JSONField(blank=True, max_length=50, null=True),
        ),
    ]
