# Generated by Django 5.1.8 on 2025-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_alter_jiraissue_time_mined'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
