# Generated by Django 5.1.8 on 2025-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_jiraissue_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='activity_log',
            field=models.JSONField(blank=True, default=list, help_text='Registro de atividades da issue', null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Checklist com informações de datas', null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='Histórico de alterações da issue', null=True),
        ),
    ]
