# Generated by Django 5.1.8 on 2025-05-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_jiraissue_activity_log_jiraissue_checklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_value', models.CharField(max_length=100)),
                ('from_value', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='JiraChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField()),
                ('progress', models.CharField(max_length=50)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JiraComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JiraCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('repository_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JiraHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JiraHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('fieldtype', models.CharField(max_length=50)),
                ('from_value', models.CharField(blank=True, max_length=255, null=True)),
                ('to_value', models.CharField(blank=True, max_length=255, null=True)),
                ('fromString', models.TextField(blank=True, null=True)),
                ('toString', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=50)),
                ('link_direction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuetype', models.CharField(max_length=100)),
                ('issuetype_description', models.TextField(blank=True, null=True)),
                ('hierarchyLevel', models.IntegerField(default=0)),
                ('subtask', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('simplified', models.BooleanField()),
                ('projectTypeKey', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JiraSprint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
                ('boardId', models.IntegerField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('completeDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('accountId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=255)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('timeZone', models.CharField(max_length=100)),
                ('accountType', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='jiraissue',
            name='unique_issue',
        ),
        migrations.AlterUniqueTogether(
            name='jiraissue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='parent_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='timeestimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='timeoriginalestimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='timespent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='issue_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='priority',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jiraactivitylog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jirachecklist',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jiracomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jiracommit',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jirahistory',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jirahistoryitem',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jirahistory'),
        ),
        migrations.AddField(
            model_name='jiraissuelink',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jiraissuelink',
            name='linked_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraproject'),
        ),
        migrations.AddField(
            model_name='jirasprint',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.jiraissue'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to='jira.jirauser'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='jira.jirauser'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='jira.jirauser'),
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='activity_log',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='all_fields',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='commits',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='history',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='issuetype',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='issuetype_description',
        ),
    ]
