# Generated by Django 5.1.8 on 2025-05-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0006_jiraactivitylog_jirachecklist_jiracomment_jiracommit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
