# Generated by Django 5.1.8 on 2025-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0007_alter_jiraissue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraactivitylog',
            name='from_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jiraactivitylog',
            name='to_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
