# Generated by Django 5.1.8 on 2025-05-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0008_alter_jiraactivitylog_from_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jirasprint',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jirasprint',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
