# Generated by Django 5.1.8 on 2025-06-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0009_alter_jirasprint_enddate_alter_jirasprint_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jirasprint',
            name='issue',
        ),
        migrations.AddField(
            model_name='jirasprint',
            name='issues',
            field=models.ManyToManyField(related_name='sprints', to='jira.jiraissue'),
        ),
        migrations.AlterField(
            model_name='jirasprint',
            name='boardId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='jirasprint',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jirasprint',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
