# Generated by Django 5.1.8 on 2025-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='token_validation_error',
            field=models.BooleanField(default=False),
        ),
    ]
