# Generated by Django 5.1.8 on 2025-06-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_task_error_type_task_token_validation_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='operation',
            field=models.TextField(),
        ),
    ]
