# Generated by Django 5.1.8 on 2025-08-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_task_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repository',
            field=models.CharField(max_length=255),
        ),
    ]
