# Generated by Django 5.1.8 on 2025-08-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_task_operation'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repository_name',
            field=models.CharField(default='', help_text='Nome do repositório para casos onde Repository não existe', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='utils.repository'),
        ),
    ]
