[package]
name = "rust-code"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3.2"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.15"
rayon = "1.5"
git2 = "0.14"
chrono = "0.4"
egui = "0.21"
eframe = "0.21"