# Generated by Django 5.1.8 on 2026-02-24 19:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackQuestion',
            fields=[
                ('question_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('up_vote_count', models.IntegerField(default=0)),
                ('down_vote_count', models.IntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('content_license', models.CharField(max_length=50, null=True)),
                ('share_link', models.URLField(null=True)),
                ('body_markdown', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('favorite_count', models.IntegerField(default=0)),
                ('accepted_answer_id', models.BigIntegerField(null=True)),
                ('time_mined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'stack_question',
            },
        ),
        migrations.CreateModel(
            name='StackUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255, null=True)),
                ('reputation', models.IntegerField(default=0)),
                ('profile_image', models.URLField(null=True)),
                ('user_type', models.CharField(max_length=50, null=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('last_access_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(null=True)),
                ('accept_rate', models.IntegerField(null=True)),
                ('about_me', models.TextField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('website_url', models.URLField(null=True)),
                ('account_id', models.BigIntegerField(null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('down_vote_count', models.IntegerField(default=0)),
                ('up_vote_count', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('question_count', models.IntegerField(default=0)),
                ('reputation_change_year', models.IntegerField(default=0)),
                ('reputation_change_quarter', models.IntegerField(default=0)),
                ('reputation_change_month', models.IntegerField(default=0)),
                ('reputation_change_week', models.IntegerField(default=0)),
                ('reputation_change_day', models.IntegerField(default=0)),
                ('time_mined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'stack_user',
            },
        ),
        migrations.CreateModel(
            name='StackAnswer',
            fields=[
                ('answer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('up_vote_count', models.IntegerField(default=0)),
                ('down_vote_count', models.IntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('content_license', models.CharField(max_length=50, null=True)),
                ('share_link', models.URLField()),
                ('body_markdown', models.TextField()),
                ('link', models.URLField()),
                ('title', models.TextField()),
                ('time_mined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='stackoverflow.stackquestion')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='stackoverflow.stackuser')),
            ],
            options={
                'db_table': 'stack_answer',
            },
        ),
        migrations.CreateModel(
            name='StackQuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackquestion')),
            ],
            options={
                'db_table': 'stack_question_tag',
            },
        ),
        migrations.CreateModel(
            name='StackTag',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('has_synonyms', models.BooleanField(default=False)),
                ('is_moderator_only', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions', models.ManyToManyField(through='stackoverflow.StackQuestionTag', to='stackoverflow.stackquestion')),
            ],
            options={
                'db_table': 'stack_tag',
            },
        ),
        migrations.AddField(
            model_name='stackquestiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stacktag'),
        ),
        migrations.AddField(
            model_name='stackquestion',
            name='tags',
            field=models.ManyToManyField(through='stackoverflow.StackQuestionTag', to='stackoverflow.stacktag'),
        ),
        migrations.AddField(
            model_name='stackquestion',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='stackoverflow.stackuser'),
        ),
        migrations.CreateModel(
            name='StackComment',
            fields=[
                ('comment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(max_length=10)),
                ('post_id', models.BigIntegerField()),
                ('body', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('content_license', models.CharField(max_length=50)),
                ('edited', models.BooleanField(default=False)),
                ('body_markdown', models.TextField()),
                ('link', models.URLField()),
                ('time_mined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stackoverflow.stackanswer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stackoverflow.stackquestion')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='stackoverflow.stackuser')),
            ],
            options={
                'db_table': 'stack_comment',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stackquestiontag',
            unique_together={('question', 'tag')},
        ),
    ]
