# Generated by Django 5.1.8 on 2026-01-26 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackBadge',
            fields=[
                ('badge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('badge_type', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'stack_badge',
            },
        ),
        migrations.CreateModel(
            name='StackCollective',
            fields=[
                ('slug', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stack_collective',
            },
        ),
        migrations.AddField(
            model_name='stackuser',
            name='badge_counts',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='stackuser',
            name='collectives',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='StackCollectiveTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.ForeignKey(db_column='collective_slug', on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackcollective')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stacktag')),
            ],
            options={
                'db_table': 'stack_collective_tag',
                'unique_together': {('collective', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='stackcollective',
            name='tags',
            field=models.ManyToManyField(through='stackoverflow.StackCollectiveTag', to='stackoverflow.stacktag'),
        ),
        migrations.CreateModel(
            name='StackCollectiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('collective', models.ForeignKey(db_column='collective_slug', on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackcollective')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackuser')),
            ],
            options={
                'db_table': 'stack_collective_user',
                'unique_together': {('collective', 'user')},
            },
        ),
        migrations.AddField(
            model_name='stackcollective',
            name='users',
            field=models.ManyToManyField(through='stackoverflow.StackCollectiveUser', to='stackoverflow.stackuser'),
        ),
        migrations.CreateModel(
            name='StackUserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackuser')),
            ],
            options={
                'db_table': 'stack_user_badge',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='stackbadge',
            name='users',
            field=models.ManyToManyField(through='stackoverflow.StackUserBadge', to='stackoverflow.stackuser'),
        ),
        migrations.CreateModel(
            name='StackTagSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stacktag')),
            ],
            options={
                'db_table': 'stack_tag_synonym',
                'unique_together': {('tag', 'synonym')},
            },
        ),
    ]
