# Generated by Django 5.1.8 on 2025-06-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackquestion',
            name='accepted_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_questions', to='stackoverflow.stackanswer'),
        ),
    ]
