# Generated by Django 5.1.8 on 2025-06-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0002_stackquestion_accepted_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackquestion',
            name='owner',
            field=models.BigIntegerField(null=True),
        ),
    ]
