# Generated by Django 5.1.8 on 2025-06-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0003_alter_stackquestion_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackquestion',
            name='accepted_answer',
        ),
        migrations.RemoveField(
            model_name='stackquestion',
            name='tags',
        ),
    ]
