# Generated by Django 5.1.8 on 2025-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0004_remove_stackquestion_accepted_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackquestion',
            name='body_markdown',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='last_activity_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='share_link',
            field=models.URLField(null=True),
        ),
    ]
