# Generated by Django 5.1.8 on 2025-06-09 00:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0005_alter_stackquestion_body_markdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackquestion',
            name='tags',
            field=models.ManyToManyField(through='stackoverflow.StackQuestionTag', to='stackoverflow.stacktag'),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='stackoverflow.stackuser'),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='time_mined',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
