# Generated by Django 5.1.8 on 2025-06-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0006_stackquestion_tags_alter_stackquestion_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackuser',
            name='account_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='badge_counts',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='collectives',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='last_access_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='last_modified_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='profile_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='stackuser',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
