# Generated by Django 5.1.8 on 2025-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0007_alter_stackuser_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacktag',
            name='last_activity_date',
            field=models.DateTimeField(null=True),
        ),
    ]
