# Generated by Django 5.1.8 on 2025-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0008_alter_stacktag_last_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackquestion',
            name='accepted_answer_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
