# Generated by Django 5.1.8 on 2025-06-14 01:21

from django.db import migrations, models


def set_time_mined_to_none(apps, schema_editor):
    StackUser = apps.get_model('stackoverflow', 'StackUser')
    StackUser.objects.all().update(time_mined=None)


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0015_alter_stackanswer_time_mined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackuser',
            name='time_mined',
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunPython(set_time_mined_to_none),
        migrations.AlterField(
            model_name='stackanswer',
            name='time_mined',
            field=models.BigIntegerField(default=1749864086),
        ),
        migrations.AlterField(
            model_name='stackcollective',
            name='last_sync',
            field=models.BigIntegerField(default=1749864086),
        ),
        migrations.AlterField(
            model_name='stackcomment',
            name='time_mined',
            field=models.BigIntegerField(default=1749864086),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='time_mined',
            field=models.BigIntegerField(default=1749864086, null=True),
        ),
        migrations.AlterField(
            model_name='stacktag',
            name='last_sync',
            field=models.BigIntegerField(default=1749864086),
        ),
    ]
