# Generated by Django 5.1.8 on 2025-06-16 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0018_alter_stackanswer_time_mined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackcollective',
            name='id',
        ),
        migrations.AlterField(
            model_name='stackanswer',
            name='time_mined',
            field=models.BigIntegerField(default=1750087226),
        ),
        migrations.AlterField(
            model_name='stackcollective',
            name='last_sync',
            field=models.BigIntegerField(default=1750087226),
        ),
        migrations.AlterField(
            model_name='stackcollective',
            name='slug',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stackcollectivetag',
            name='collective',
            field=models.ForeignKey(db_column='collective_slug', on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackcollective'),
        ),
        migrations.AlterField(
            model_name='stackcollectiveuser',
            name='collective',
            field=models.ForeignKey(db_column='collective_slug', on_delete=django.db.models.deletion.CASCADE, to='stackoverflow.stackcollective'),
        ),
        migrations.AlterField(
            model_name='stackcomment',
            name='time_mined',
            field=models.BigIntegerField(default=1750087226),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='time_mined',
            field=models.BigIntegerField(default=1750087226, null=True),
        ),
        migrations.AlterField(
            model_name='stacktag',
            name='last_sync',
            field=models.BigIntegerField(default=1750087226),
        ),
    ]
