# Generated by Django 5.1.8 on 2025-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0046_alter_stackanswer_time_mined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackanswer',
            name='time_mined',
            field=models.BigIntegerField(default=1754937794),
        ),
        migrations.AlterField(
            model_name='stackcollective',
            name='last_sync',
            field=models.BigIntegerField(default=1754937794),
        ),
        migrations.AlterField(
            model_name='stackcomment',
            name='time_mined',
            field=models.BigIntegerField(default=1754937794),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='time_mined',
            field=models.BigIntegerField(default=1754937794, null=True),
        ),
        migrations.AlterField(
            model_name='stacktag',
            name='last_sync',
            field=models.BigIntegerField(default=1754937794),
        ),
    ]
