# Generated by Django 5.1.8 on 2025-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0065_alter_stackanswer_time_mined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackProject',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='Mineração de dados da plataforma Stack Overflow.', null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stack_project',
            },
        ),
        migrations.AlterField(
            model_name='stackanswer',
            name='time_mined',
            field=models.BigIntegerField(default=1757513559),
        ),
        migrations.AlterField(
            model_name='stackcollective',
            name='last_sync',
            field=models.BigIntegerField(default=1757513559),
        ),
        migrations.AlterField(
            model_name='stackcomment',
            name='time_mined',
            field=models.BigIntegerField(default=1757513559),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='time_mined',
            field=models.BigIntegerField(default=1757513559, null=True),
        ),
        migrations.AlterField(
            model_name='stacktag',
            name='last_sync',
            field=models.BigIntegerField(default=1757513559),
        ),
    ]
