# Generated by Django 5.1.8 on 2025-09-29 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stackoverflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stackanswer",
            name="time_mined",
            field=models.DateTimeField(
                blank=True,
                null=True,
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="stackcollective",
            name="last_sync",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="stackcomment",
            name="time_mined",
            field=models.DateTimeField(
                blank=True,
                null=True,
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="stackquestion",
            name="time_mined",
            field=models.DateTimeField(
                blank=True,
                null=True,
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="stacktag",
            name="last_sync",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
            ),
        ),
    ]
