# Generated by Django 5.1.8 on 2026-01-05 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0079_alter_stackanswer_time_mined_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stackcollectivetag',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='stackcollectiveuser',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='stacktagsynonym',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='stackuserbadge',
            unique_together=None,
        ),

        migrations.RemoveField(
            model_name='stackuserbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='stackcollective',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='stackcollective',
            name='users',
        ),
        migrations.RemoveField(
            model_name='stackcollectiveuser',
            name='collective',
        ),
        migrations.RemoveField(
            model_name='stackcollectivetag',
            name='collective',
        ),
        migrations.RemoveField(
            model_name='stackcollectivetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='stackcollectiveuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stacktagsynonym',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='stackuserbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stackuser',
            name='badge_counts',
        ),
        migrations.RemoveField(
            model_name='stackuser',
            name='collectives',
        ),

        migrations.AlterField(
            model_name='stackanswer',
            name='time_mined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stackcomment',
            name='time_mined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stackquestion',
            name='time_mined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stacktag',
            name='last_sync',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),

        migrations.DeleteModel(
            name='StackBadge',
        ),
        migrations.DeleteModel(
            name='StackCollective',
        ),
        migrations.DeleteModel(
            name='StackCollectiveTag',
        ),
        migrations.DeleteModel(
            name='StackCollectiveUser',
        ),
        migrations.DeleteModel(
            name='StackTagSynonym',
        ),
        migrations.DeleteModel(
            name='StackUserBadge',
        ),
    ]
