# Generated by Django 5.1 on 2024-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_path', models.CharField(max_length=500)),
                ('mine_commits', models.BooleanField(default=False)),
                ('mine_docs', models.BooleanField(default=False)),
                ('mine_code', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('mining_result', models.TextField(blank=True, null=True)),
                ('process_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ssh_url', models.CharField(max_length=255)),
                ('tipo_mineracao', models.CharField(max_length=50)),
                ('dados', models.JSONField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tamanho', models.BigIntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('num_commits', models.IntegerField()),
            ],
        ),
    ]
