# Generated by Django 5.1 on 2024-09-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositorio',
            options={'managed': False},
        ),
    ]
