# Generated by Django 5.1 on 2024-10-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_repositorio_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repositorio',
            table='repositorios',
        ),
    ]
