# Generated by Django 5.1 on 2024-11-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='githubcommit',
            name='author_name',
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='deletions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='dmm_unit_complexity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='dmm_unit_interfacing',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='dmm_unit_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='files_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='in_main_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='insertions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='githubcommit',
            name='sha',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='issue_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_commits', to='github.githubauthor'),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='committer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committer_commits', to='github.githubauthor'),
        ),
        migrations.CreateModel(
            name='GitHubModifiedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.TextField(null=True)),
                ('new_path', models.TextField(null=True)),
                ('filename', models.TextField()),
                ('change_type', models.CharField(max_length=20)),
                ('diff', models.TextField(null=True)),
                ('added_lines', models.IntegerField()),
                ('deleted_lines', models.IntegerField()),
                ('complexity', models.IntegerField(null=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_files', to='github.githubcommit')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complexity', models.IntegerField(null=True)),
                ('max_nesting', models.IntegerField(null=True)),
                ('modified_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='github.githubmodifiedfile')),
            ],
        ),
    ]
