# Generated by Django 5.1.8 on 2025-04-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubissuepullrequest',
            old_name='tipo',
            new_name='data_type',
        ),
    ]
