# Generated by Django 5.1.8 on 2025-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_rename_tipo_githubissuepullrequest_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubbranch',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
        migrations.AlterField(
            model_name='githubcommit',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
        migrations.AlterField(
            model_name='githubissuepullrequest',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
        migrations.AlterField(
            model_name='githubmetadata',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
        migrations.AlterField(
            model_name='githubmethod',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
        migrations.AlterField(
            model_name='githubmodifiedfile',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='time_mined',
            field=models.DateTimeField(help_text='Date and time of mining', null=True),
        ),
    ]
