# Generated by Django 5.1 on 2025-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_githubauthor_remove_githubcommit_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubmethod',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
