# Generated by Django 5.1 on 2025-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_alter_githubmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubauthor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='githubauthor',
            unique_together={('name', 'email')},
        ),
    ]
