# Generated by Django 5.1.8 on 2025-05-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_alter_githubbranch_time_mined_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='githubmetadata',
            unique_together={('repository', 'owner')},
        ),
    ]
