# Generated by Django 5.1.8 on 2025-08-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_alter_githubmetadata_unique_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='githubissue',
            new_name='github_gith_reposit_85164d_idx',
            old_name='github_gith_reposit_680a4b_idx',
        ),
        migrations.RenameIndex(
            model_name='githubissuepullrequest',
            new_name='github_gith_reposit_43f809_idx',
            old_name='github_gith_reposit_a7991d_idx',
        ),
        migrations.AlterField(
            model_name='githubbranch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github.githubmetadata'),
        ),
        migrations.AlterField(
            model_name='githubcommit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github.githubmetadata'),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='github.githubmetadata'),
        ),
        migrations.AlterField(
            model_name='githubissuepullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_and_prs', to='github.githubmetadata'),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github.githubmetadata'),
        ),
    ]
