# Generated by Django 5.1.8 on 2025-08-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_alter_githubmetadata_unique_together'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='githubissue',
            new_name='github_gith_reposit_85164d_idx',
            old_name='github_gith_reposit_680a4b_idx',
        ),
        migrations.RenameIndex(
            model_name='githubissuepullrequest',
            new_name='github_gith_reposit_43f809_idx',
            old_name='github_gith_reposit_a7991d_idx',
        ),
        migrations.RenameIndex(
            model_name='githubmetadata',
            new_name='github_gith_reposit_d16320_idx',
            old_name='github_gith_reposit_4a8a5f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='githubmetadata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='githubbranch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='utils.repository'),
        ),
        migrations.AlterField(
            model_name='githubcommit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='utils.repository'),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='github.githubauthor'),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='utils.repository'),
        ),
        migrations.AlterField(
            model_name='githubissuepullrequest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues_and_prs', to='github.githubauthor'),
        ),
        migrations.AlterField(
            model_name='githubissuepullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_and_prs', to='utils.repository'),
        ),
        migrations.AlterField(
            model_name='githubmetadata',
            name='repository',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_metadata', to='utils.repository'),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pull_requests', to='github.githubauthor'),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='utils.repository'),
        ),
    ]
