# Generated by Django 5.1 on 2025-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_githubbranch_repository_githubcommit_repository_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
