# Generated by Django 5.1.8 on 2025-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_rename_github_gith_reposit_680a4b_idx_github_gith_reposit_85164d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubbranch',
            name='repository_name',
            field=models.CharField(blank=True, help_text='Nome do repositório para consultas rápidas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='repository_name',
            field=models.CharField(blank=True, help_text='Nome do repositório para consultas rápidas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='repository_name',
            field=models.CharField(blank=True, help_text='Nome do repositório para consultas rápidas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubissuepullrequest',
            name='repository_name',
            field=models.CharField(blank=True, help_text='Nome do repositório para consultas rápidas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='repository_name',
            field=models.CharField(blank=True, help_text='Nome do repositório para consultas rápidas', max_length=255, null=True),
        ),
    ]
