# Generated by Django 5.1 on 2025-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_alter_githubpullrequest_pr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubissue',
            name='issue_id',
            field=models.BigIntegerField(),
        ),
    ]
