# Generated by Django 5.1.8 on 2025-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_githubbranch_repository_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='githubissue',
            name='github_gith_created_dd1287_idx',
        ),
        migrations.RemoveIndex(
            model_name='githubissuepullrequest',
            name='github_gith_created_c0cefb_idx',
        ),
        migrations.RemoveIndex(
            model_name='githubmetadata',
            name='github_gith_created_c095ab_idx',
        ),
        migrations.RenameField(
            model_name='githubissue',
            old_name='created_at',
            new_name='github_created_at',
        ),
        migrations.RenameField(
            model_name='githubissuepullrequest',
            old_name='created_at',
            new_name='github_created_at',
        ),
        migrations.RenameField(
            model_name='githubmetadata',
            old_name='created_at',
            new_name='github_created_at',
        ),
        migrations.RenameField(
            model_name='githubpullrequest',
            old_name='created_at',
            new_name='github_created_at',
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['github_created_at'], name='github_gith_github__d8a52d_idx'),
        ),
        migrations.AddIndex(
            model_name='githubissuepullrequest',
            index=models.Index(fields=['github_created_at'], name='github_gith_github__42a901_idx'),
        ),
        migrations.AddIndex(
            model_name='githubmetadata',
            index=models.Index(fields=['github_created_at'], name='github_gith_github__54df90_idx'),
        ),
    ]
