# Generated by Django 5.1 on 2025-01-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_alter_githubissue_issue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubmethod',
            name='name',
            field=models.TextField(),
        ),
    ]
