# Generated by Django 5.1.8 on 2025-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_rename_created_at_to_github_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='githubissue',
            name='github_gith_updated_5e648d_idx',
        ),
        migrations.RemoveIndex(
            model_name='githubissuepullrequest',
            name='github_gith_updated_036249_idx',
        ),
        migrations.RemoveIndex(
            model_name='githubmetadata',
            name='github_gith_updated_83a92e_idx',
        ),
        migrations.RenameField(
            model_name='githubissue',
            old_name='updated_at',
            new_name='github_updated_at',
        ),
        migrations.RenameField(
            model_name='githubissuepullrequest',
            old_name='updated_at',
            new_name='github_updated_at',
        ),
        migrations.RenameField(
            model_name='githubmetadata',
            old_name='updated_at',
            new_name='github_updated_at',
        ),
        migrations.RenameField(
            model_name='githubpullrequest',
            old_name='updated_at',
            new_name='github_updated_at',
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['github_updated_at'], name='github_gith_github__04a7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='githubissuepullrequest',
            index=models.Index(fields=['github_updated_at'], name='github_gith_github__6c0bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='githubmetadata',
            index=models.Index(fields=['github_updated_at'], name='github_gith_github__ac671a_idx'),
        ),
    ]
