# Generated by Django 5.1 on 2025-01-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0010_remove_githubpullrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubissue',
            name='assignees',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='author_association',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='is_pull_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='labels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='milestone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='timeline_events',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['repository', 'issue_id'], name='github_gith_reposit_680a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['created_at'], name='github_gith_created_dd1287_idx'),
        ),
        migrations.AddIndex(
            model_name='githubissue',
            index=models.Index(fields=['updated_at'], name='github_gith_updated_5e648d_idx'),
        ),
    ]
