# Generated by Django 5.1 on 2025-01-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0011_githubissue_assignees_githubissue_author_association_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubissue',
            name='title',
            field=models.TextField(),
        ),
    ]
