# Generated by Django 5.1 on 2025-02-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0013_githubpullrequest_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(db_index=True, max_length=255)),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('watchers_count', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=100, null=True)),
                ('topics', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('homepage', models.URLField(null=True)),
                ('license', models.CharField(max_length=100, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['repository'], name='github_gith_reposit_4a8a5f_idx'), models.Index(fields=['created_at'], name='github_gith_created_c095ab_idx'), models.Index(fields=['updated_at'], name='github_gith_updated_83a92e_idx')],
            },
        ),
    ]
