# Generated by Django 5.1 on 2025-02-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0014_githubmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubmetadata',
            name='releases_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubmetadata',
            name='used_by_count',
            field=models.IntegerField(default=0),
        ),
    ]
