# Generated by Django 5.1 on 2025-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0015_githubmetadata_releases_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
