# Generated by Django 5.1 on 2025-02-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0016_alter_githubpullrequest_pr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubbranch',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
