# Generated by Django 5.1 on 2025-03-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0017_alter_githubbranch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubbranch',
            name='time_mined',
            field=models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='time_mined',
            field=models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='time_mined',
            field=models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
        migrations.AddField(
            model_name='githubmetadata',
            name='time_mined',
            field=models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
        migrations.AddField(
            model_name='githubmethod',
            name='time_mined',
            field=models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
        migrations.AddField(
            model_name='githubmodifiedfile',
            name='time_mined',
            field=models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='time_mined',
            field=models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True),
        ),
    ]
