# Generated by Django 5.1 on 2025-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0018_githubbranch_time_mined_githubcommit_time_mined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIssuePullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(db_index=True, default='', max_length=255)),
                ('record_id', models.BigIntegerField(unique=True)),
                ('number', models.IntegerField(null=True)),
                ('title', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=100)),
                ('assignees', models.JSONField(default=list)),
                ('labels', models.JSONField(default=list)),
                ('milestone', models.CharField(blank=True, max_length=255, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('comments', models.JSONField(default=list)),
                ('timeline_events', models.JSONField(default=list)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('commits', models.JSONField(default=list)),
                ('is_pull_request', models.BooleanField(default=False)),
                ('author_association', models.CharField(blank=True, max_length=50, null=True)),
                ('reactions', models.JSONField(default=dict)),
                ('tipo', models.CharField(max_length=20)),
                ('time_mined', models.FloatField(help_text='Timestamp Unix da mineração em segundos', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['repository', 'record_id'], name='github_gith_reposit_a7991d_idx'), models.Index(fields=['created_at'], name='github_gith_created_c0cefb_idx'), models.Index(fields=['updated_at'], name='github_gith_updated_036249_idx')],
            },
        ),
    ]
