# Generated by Django 5.1.8 on 2025-08-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Nome completo do repositório (ex: 'owner/repo' para GitHub, 'project-key' para Jira)", max_length=255, unique=True)),
                ('owner', models.CharField(help_text='Proprietário ou organização', max_length=255)),
                ('name', models.CharField(help_text='Nome do repositório', max_length=255)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('jira', 'Jira')], help_text='Plataforma onde o repositório está hospedado', max_length=20)),
                ('url', models.URLField(blank=True, help_text='URL do repositório', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'ordering': ['platform', 'full_name'],
                'indexes': [models.Index(fields=['platform', 'full_name'], name='utils_repos_platfor_784d9d_idx'), models.Index(fields=['owner'], name='utils_repos_owner_a4b9d9_idx')],
            },
        ),
    ]
