# Generated by Django 5.1.8 on 2025-08-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
